### ISSUE TITLE
Hello, can this tool discover common admin.zip web.zip backup files

### ISSUE THREAD

**Issue by Hel10-Web** [musana/fuzzuli#11]
During a penetration test, the admin.zip file could not be found. Does this tool support common backup file dictionaries?

**Comment by musana** [comment]
fuzzuli generates a wordlist based on a given domain. in order to generate admin.zip the given domain contains admin keyword otherwise it doesn't support common backup file name. This is exactly what distinguishes fuzzuli from other traditional brute-force tools.

**Comment by Sh4d0wHunt3rX** [comment]
Hey, thanks for the script. Maybe you can also add common backup file names? So, we can run only this tool for backup : )

**Comment by musana** [comment]
It's in the to-do. with the next releases, it will be added. thank you for your feedback 🙌

**Comment by Sh4d0wHunt3rX** [comment]
Musana, is it possible to add ETA to see when the fuzzing will be finished? Currently only shows the number of iterations per second.

**Comment by musana** [comment]
Currently, it's not possible to know when the scan is finished but with the next release, a new function will be added which calculates the total number of requests that will be sent

**Comment by Sh4d0wHunt3rX** [comment]
Thanks a lot, I had some other questions:

Does your proxy accept socks5? 
Is it possible to increase the concurrency?
Does localhost accept IPV6?
If I use echo https://fuzzuli.musana.net | fuzzuli -p , which method it's using among those 7 methods?

**Comment by musana** [comment]
Hi,
- Currently, it only supports http/s proxy. 
- with -w parameter you can increase the goroutine count.
- The default method is shuffle

**Comment by musana** [comment]
I'm closing the issue because the question has been answered.
