### ISSUE TITLE
Is it normal that I don't see any output, or the output I see is only when the tool finds something, and it doesn't show false results?

### ISSUE THREAD

**Issue by sa-a9** [musana/fuzzuli#12]

**Comment by sa-a9** [comment]
![photo_2023-12-21_05-08-48](https://github.com/musana/fuzzuli/assets/117305594/e3c76e70-f6d9-41f2-b26f-78ade73b9f21)

**Comment by omar6667** [comment]
![Uploading photo_2023-12-21_05-08-40.jpg…]()

**Comment by musana** [comment]
to view the request that the tool sends pass the "-p" flag.

**Comment by sa-a9** [comment]
You are right. I apologize for the misunderstanding
