### ISSUE TITLE
"Something went wrong…" in Cmder on Windows10

### ISSUE THREAD

**Issue by scillidan** [musana/fuzzuli#2]
Run it in [Cmder](https://cmder.app) and it say:
![image](https://user-images.githubusercontent.com/19889610/185153142-9ce6bf87-18d4-48ed-b6a1-1de270c68092.png)

**Comment by musana** [comment]
Could you try again? v1.1.1 was released.

**Comment by scillidan** [comment]
Thanks :)
It works now.
