### ISSUE TITLE
print only without sending the request

### ISSUE THREAD

**Issue by mk7120** [musana/fuzzuli#5]
Can you support the option for printing urls only without send the request?

**Comment by musana** [comment]
This feature is on my to-do list. I am very busy these days, but I will add it as soon as possible.

**Comment by musana** [comment]
Since "just wordlist generation" mode is added I'm closing the issue. To reach more details about that please just visit release notes.

Thanks

**Comment by musana** [comment]
Since "just wordlist generation" mode is added I'm closing the issue. To reach more details about that please just visit release notes.

Thanks
