### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by sl4x0** [musana/fuzzuli#7]
- My first time using this tool this happened:

```bash
fuzzuli -f roots.txt  -w 32 -ex .rar,.zip -p

  __                               _   _ 
 / _|                             | | (_)
| |_   _   _   ____  ____  _   _  | |  _ 
|  _| | | | | |_  / |_  / | | | | | | | |
| |   | |_| |  / /   / /  | |_| | | | | |
|_|    \__,_| /___| /___|  \__,_| |_| |_|

musana.net | @musana
--------------------------------------------

[*] Scan starting time: 2023-03-13 11:28:08
panic: runtime error: index out of range [1] with length 1

goroutine 7 [running]:
main.shuffle({0xc00001e3f0, 0x16}, 0x0?)
        /go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:183 +0x193
main.getAllCombination({0xc00001e3f0, 0x16})
        /go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:123 +0x1f4
main.start({0xc00001e3f0, 0x16})
        /go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:98 +0x9c
main.main.func1()
        /go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:88 +0x25
github.com/gammazero/workerpool.startWorker(0x0?, 0xc00002a120)
        /go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:233 +0x22
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
        /go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:195 +0x25a
```

**Comment by dimonl** [comment]
could you please provide you 'roots.txt' to test needed changes

**Comment by sl4x0** [comment]
It contains "hackerone.com"

**Comment by musana** [comment]
Each domain in the roots.txt file must start with http:// or https://

**Comment by dimonl** [comment]
there is another strange behaviour in that case if you have "https" here - it always automatically transform in "http"
[https://github.com/musana/fuzzuli/blob/aa4936f33d8b740ad4aed96c629037c449c77fa2/fuzzuli.go#L186](url)

**Comment by musana** [comment]
Hi @dimonl ,

You make an excellent point :) Actually, it doesn't matter the point you mentioned. It's just a dummy value to do parsing properly. If you pay attention to generatePossibilities function which is in 245. line it splits domain from "://" and only process the second part(array index is 1). Finally, it takes schema information(http or https) from the user's data which is provided in file or stdin

Also, you can test with domain that doesn't accept http connection. If it convert to http as you mention, the connection couldn't have been made. you can see that the request was sent successfully :)

**Comment by dimonl** [comment]
cool, thanks. in this case you can transform input domains in  url objects (using net/url) and validate them. Url will be parsed automatically and in this case you can avoid usage of non proper domains and avoid panic as at this bug, because taking array's values using index is not the best way.
