### ISSUE TITLE
github.com/musana/fuzzuli@latest: module github.com/musana/fuzzuli: Get "https://proxy.golang.org/github.com/musana/fuzzuli/@v/list":

### ISSUE THREAD

**Issue by Done461** [musana/fuzzuli#8]
![image](https://user-images.githubusercontent.com/52113967/233696895-0c854c4c-eb61-4189-8809-f7a9a36de3ee.png)

any idea ??

**Comment by musana** [comment]
I didn't face something that. Seems like it's regarding your internet connection.
