### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with 

### ISSUE THREAD

**Issue by pprogg** [musana/fuzzuli#9]
Unsolicited response received on idle HTTP channel starting with 

![image](https://github.com/musana/fuzzuli/assets/133516192/85b2eec1-f6aa-4fec-89e7-edf1357f0218)

**Comment by musana** [comment]
Hello @pprogg ,

Seems like HTTP HEAD request returns body in response. I will handle it as soon as possible.

Thanks
